<a href="https://colab.research.google.com/github/thecodingAdi/ai-ml-playground/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas  as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('train.txt',sep = ';', header = None, names = ['text', 'emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [8]:
unique_emotions = df['emotion'].unique()

In [9]:
emotion_numbers = {}
i =0
for emotion in unique_emotions:
    emotion_numbers[emotion] = i
    i+=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [11]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

### Text Cleaning - Lower casing

In [12]:
df['text'] = df['text'].apply(lambda x : x.lower())

###  Remove punctuation

In [17]:
import string
def remove_punc(text):
  return text.translate(str.maketrans('','',string.punctuation))

In [20]:
df['text'] = df['text'].apply(remove_punc)

### Remove numbers

In [21]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new+=i
  return new

df['text'] = df['text'].apply(remove_number)

### Remove URl, Remove HTML Tags

### Remove Emojis

In [24]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new+=i
  return new

df['text'] = df['text'].apply(remove_emojis)

### Remove Stopward

In [25]:
import nltk

In [26]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [27]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [29]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [30]:
df.loc[1] ['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [34]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned =[]
  for word in words:
    if not word in stop_words:
      cleaned.append(word)
  return ' '.join(cleaned)

In [36]:
nltk.download('punkt_tab')
df['text'] = df['text'].apply(remove)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [37]:
df.loc[1] ['text']

'go feeling hopeless damned hopeful around someone cares awake'